Hexbin recipe
MakieOrg/Makie.jl pull request #2201
Opened 2022-08-05 10:37 UTC by TabeaW

# Description

Adds the recipe for hexbin plots (#368) with documentation.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist

- [ ] Added an entry in NEWS.md (for new features and breaking changes)
- [x] Added or changed relevant sections in the documentation
- [ ] Added unit tests for new algorithms, conversion methods, etc.
- [ ] Added reference image tests for new plotting functions, recipes, visual options, etc.

2022-08-08 06:02 UTC, TabeaW commented
As this is my first work in Makie, it would be great if someone experienced can have a look at this :) I am not quite sure, if I had done reasonable work with the axis :D

2022-08-08 14:22 UTC, jkrumbiegel commented
Very cool, thank you, I'll try to take a look soon when I have some spare time.

2022-08-16 11:08 UTC, jkrumbiegel commented
For some inputs I get an empty line (usually second to topmost it seems?)

```julia
x = [-0.8229475043895498, -0.46621767925243984, -2.0720758196284805, 0.524687403763896, 0.9653685757558091, 1.7528735168451055, -0.33237984203429993, 0.3506865765367531, -0.8944929017899972, 0.2532684038441482]
y = [-1.7463655960215445, 1.8957111366590151, 0.5550468594781066, 1.2254393653690707, 1.371174685353981, -1.0206975175484125, 0.3360700428234833, 2.195537222554637, 0.9952661972027315, 0.28852172975641416]
hexbin(x, y)
```

![image](https://user-images.githubusercontent.com/22495855/184865235-5f4d8641-83ed-4c84-ada3-08a2ec4d57ac.png)

2022-08-16 11:24 UTC, jkrumbiegel requested changes

2022-08-16 11:24 UTC, jkrumbiegel commented on src/stats/hexbin.jl
> +        axis = current_axis()
What exactly do you need the axis for? It looks like you're trying to access its limits? First of all, `current_axis()` isn't necessarily the axis you're currently plotting to, so you can't use that. Second, you're not supposed to access any axis stuff in a recipe, it lives a level below that in a simple Scene. (At least how recipes currently work). And third, you are only doing your calculation once, so if the limits changed the plot wouldn't update. You can access limits via the projection matrix of the Scene if you really need to (check out vlines etc for how it's done there) but it's kind of rare that we do this.

2022-08-16 11:24 UTC, jkrumbiegel commented on src/stats/hexbin.jl
> +    polys = Observable(Polygon[])
Polygon is an abstract type so this doesn't really help in terms of type stability.

2022-08-16 11:24 UTC, jkrumbiegel commented on src/stats/hexbin.jl
> +            push!(polys[],b)
looks like you could also just `append!(polys[], hex)`? But anyway this would accumulate if you updated, so I'm not sure you want that

2022-08-16 11:24 UTC, jkrumbiegel commented on src/stats/hexbin.jl
> +        if isempty(count_hex[])
not sure but this probably wouldn't update if you update the plot data

2022-08-16 11:24 UTC, jkrumbiegel commented on src/stats/hexbin.jl
> +    if ! isempty(polys[])
This is also written for a static plot. In Makie, we always try to make plots update-able if possible. So you would just plot `polys` one way or another, and if the data were updated such that there are now polygons, the plot would update as well.

2022-08-16 11:24 UTC, jkrumbiegel commented on src/stats/hexbin.jl
> +        xe = sin.(0:pi/3:5/3*pi)
you don't need to allocate the vectors here, you can loop over the range below and calculate x,y on the fly

2022-08-16 11:24 UTC, jkrumbiegel commented on src/stats/hexbin.jl
> +            push!(polys[],b)
ah I see now you empty the vector above

2022-08-16 11:24 UTC, jkrumbiegel commented on src/stats/hexbin.jl
> +    calculate_grid(x[],y[],hb.gridsize[],hb.mincnt[],hb.scale[])
this is done a little more easily by just saying `notify(hb.gridsize)` or whatever

2022-08-16 11:24 UTC, jkrumbiegel commented on src/stats/hexbin.jl
> +            push!(count_hex[],a)
so you're updating the vectors but never notify the observables again, so you wouldn't see an update in a live plot

2022-08-16 11:24 UTC, jkrumbiegel commented on src/stats/hexbin.jl
> +    polys = Observable(Polygon[])
you could construct a fake poly and do `typeof(fakepoly)[]` if the type is hard to write manually (sometimes the case with GeometryBasics types I think)

2022-08-16 11:25 UTC, jkrumbiegel commented
Very good first pr, a lot of good things in there already! I made some initial comments, maybe you can clarify what the logic is supposed to be that you need limits for, I didn't quite understand from reading.

2022-08-17 07:29 UTC, TabeaW commented
Thanks a lot for the feedback!
I used the axis with its limits to cut the data. For example, if you have data points from 0:100, but you want to show only those up to 50. As, the size of the hex is calculated through the difference of min and max of axis or data. Maybe I could change the gridsize parameter, so that one can give the size and not the number of hex.
I thought that the hexbin is also updatable (I have already created a video in any case), but I will check your suggestions!

2022-08-17 08:40 UTC, jkrumbiegel commented
Yes I think it's better to decouple this from the axis limits, and have the user couple those if desired :)

2022-09-22 11:07 UTC, SimonDanisch commented
Thank you @TabeaW, we're trying to merge this in https://github.com/MakieOrg/Makie.jl/pull/2236. If you have any further improvements, you should be able to PR against that PR :)

2022-09-22 11:07 UTC, closed without merging