Add option `strip_zero` for MultiplesTicks
MakieOrg/Makie.jl pull request #4372
Opened 2024-09-17 06:11 UTC by tuncbkose

# Description

Fixes #4370

Adds a new option `strip_zero::Bool` to `MultiplesTicks` and related logic to `get_ticks` that strips labels of the form `0x` to `0`.

## Type of change

Delete options that do not apply:

- [x] New feature (non-breaking change which adds functionality)

## Checklist

- [x] Added an entry in CHANGELOG.md (for new features and breaking changes)
- [x] Added or changed relevant sections in the documentation
- [ ] Added unit tests for new algorithms, conversion methods, etc.
- [ ] Added reference image tests for new plotting functions, recipes, visual options, etc.

2024-09-17 06:27 UTC, tuncbkose commented
I'm not sure how to add tests for these, even after reading `Contributing.md` etc. If someone gives me some instructions, I'd be happy to add some.

2024-09-24 15:24 UTC, jkrumbiegel requested changes

2024-09-24 15:24 UTC, jkrumbiegel commented on src/makielayout/lineaxis.jl
> +        labs = map(x -> x[1] != '0' ? x : "0", labs)
I would check the numerical value, not the first char of the label. I don't really see lots of cases in which the char could break but it's simpler to go by the number.

2024-09-24 15:24 UTC, jkrumbiegel commented on src/makielayout/types.jl
> +MultiplesTicks(n_ideal, multiple, suffix) = MultiplesTicks(n_ideal, multiple, suffix, false)
This should get a keyword arg with default. At some number of arguments it's clearer to use keywords for the less common options. Then a reader of code has an easier time than with just a true or false

2024-09-25 08:55 UTC, jkrumbiegel approved these changes

2024-09-30 18:04 UTC, merged